[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"
authors = ["ChromoRust"]
license = "MIT OR Apache-2.0"

[dependencies]

[package.metadata.deb]
maintainer = "ChromoRust"
description = "Rust app"
depends = "$auto"
